site_name: FAANG
nav:
    - Home: index.md
    - Sample data submission:
        - Completing the template: sample/biosamples_template.md
        - Validation: sample/biosamples_validation_conversion.md
        - Submission to BioSamples: sample/biosamples_submission.md
        - Updating existing BioSamples records: sample/biosamples_updating.md
    - Sequencing data submission:
        - Completing the template: experiment/ena_template.md
        - Validation: experiment/ena_validation_conversion.md
        - Submission to ENA: experiment/ena_submission.md
        - Updating existing submission in ENA: experiment/ena_updating.md
    - Array data submission: array.md
    - Analysis data submission:
        - Completing the template: analysis/analysis_index.md
        - Validation and conversion: analysis/analysis_validation_conversion.md
    - Track Hubs submission:
        - Submitting Track Hubs: trackhubs/trackhubs_submission.md
    - Validation-Submission API:
        - Validation endpoint: api/validation.md
        - Domain actions endpoints: api/domain_actions.md
        - Submission endpoint: api/submission.md
    - Frequently Asked Questions: faq.md
theme: readthedocs
